DISTRO = "demoimages"
DISTRO_NAME = "demo images"
DISTRO_CODENAME = "wrynose"

# Bump this every time OpenEmbedded is updated!
DISTRO_VERSION = "1.0"
SDK_VENDOR = "-demoimagessdk"
SDK_VERSION := "${@'${DISTRO_VERSION}'.replace('snapshot-${METADATA_REVISION}','snapshot')}"
SDK_VERSION[vardepvalue] = "${SDK_VERSION}"

MAINTAINER = "Adam Duskett <adam.duskett@amarulasolutions.com>"

TARGET_VENDOR = "-demoimages"

REQUIRED_BBLAYERS_CONF_VERSION = "${DISTRO}-1"

LOCALCONF_VERSION = "2"

PACKAGE_CLASSES ?= "package_rpm"

SANITY_TESTED_DISTROS ?= " \
  fedora-42 \n \
  fedora-43 \n \
  fedora-44 \n \
  debian-11 \n \
  debian-12 \n \
  debian-13 \n \
"

# Set features we want. Also disables any features not explicitly mentioned.
DISTRO_FEATURES = " \
  ipv4 \
  ipv6 \
  zeroconf \
"

IMAGE_FSTYPES ?= "tar ext4 wic wic.zst wic.bmap"

QB_DEFAULT_FSTYPE = "wic"

require conf/distro/include/efi-secureboot.inc
require conf/distro/include/cve-extra-exclusions.inc
require conf/distro/include/lto.inc
require conf/distro/include/rust_security_flags.inc

INHERIT += "uninative"
