# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "demoimages-layer"
BBFILE_PATTERN_demoimages-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_demoimages-layer = "9"

LAYERDEPENDS_demoimages-layer = "core"
LAYERSERIES_COMPAT_demoimages-layer = "wrynose"
